### ISSUE TITLE
I have tested it all and a single chrome addon is better

### ISSUE THREAD

**Issue by dongerlel** [zGato/ScrewTwitchAds#1]
Just install this. No quality drop and no ads. Tested on 11.12.2023

https://chromewebstore.google.com/detail/efdkmejbldmccndljocbkmpankbjhaao

**Comment by zGato** [comment]
This extension is literally adware and does the same as VAFT. This extension has stolen open-source code for just ask for "donations" over and over. 

It also asks for very intrusive permissions, including viewing all data on all pages.

**Comment by dongerlel** [comment]
bruh stop lying, i have been using it for over 2 hours and not a single ad or a quality drop. It doesn't drop quality, i don't care if they cry for donations

**Comment by zGato** [comment]
So when you get into Twitch you don't get a notification banner about donating right? The dev, as he says in his extension description, only sends important notifications about adblocking.

**Comment by dongerlel** [comment]
why do you insult me you basement faggot?

never said i don't  see one. I actually said "i don't care if they cry for donations" learn to read

i watched over 5 different streams, i'm eu, not a single quality drop like i said

**Comment by zGato** [comment]
You're literally from Poland, you don't get ads there.

**Comment by dongerlel** [comment]
ok cool but i do get them on other streams and this addon fixes that without a quality drop. Afaik not a single one way you provided does that.

**Comment by zGato** [comment]
Get your own proxy and you'll get ad-free streaming for TTV LOL PRO or use public ones.

Poland literally has 0 ads, I use several proxies from there.
